name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # deploy on pushes to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Patch App.tsx for GitHub Pages
      - name: Patch /src/App.tsx for BrowserRouter basename
        run: |
          cp src/App.tsx src/App.tsx.bak
          sed -E "s|<BrowserRouter>|<BrowserRouter basename={import.meta.env.BASE_URL}>|" src/App.tsx > src/App.temp.tsx
          mv src/App.temp.tsx src/App.tsx

      # Step 5: Build project with dynamic Vite base
      - name: Build for GitHub Pages
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          echo "import { defineConfig } from 'vite'; import originalConfig from './vite.config'; export default defineConfig(({ mode }) => { const config = typeof originalConfig === 'function' ? originalConfig({ mode }) : originalConfig; return { ...config, base: '/' }; });" > vite.config.ghpages.ts
          npm run build -- --config vite.config.ghpages.ts

      # Step 6: Restore original App.tsx
      - name: Restore /src/App.tsx
        run: mv src/App.tsx.bak src/App.tsx

      # Step 7: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

