# .github/workflows/pages.yml
name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main        # change to your default branch if it isn't 'main'
  workflow_dispatch: {}

# Top-level permissions (important)
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: gh-pages-artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Verify dist exists
        run: |
          if [ ! -d "./dist" ]; then
            echo "ERROR: dist/ directory missing. npm run build likely failed."
            exit 1
          fi
          ls -la dist | sed -n '1,200p'

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

